version: 2.1
orbs:
  go: circleci/go@1.9.0
jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0
    resource_class: medium
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gradle-deps-{{ checksum "build.gradle" }}

      - run: gradle dependencies --no-daemon
      - run:
          name: unit
          command: gradle unit --no-daemon
      - store_test_results:
          path: ~/repo/build/test-results
      - store_artifacts:
          path: ~/repo/build/reports/tests
  integration:
    docker:
      - image: cimg/openjdk:21.0
    resource_class: medium
    working_directory: ~/repo

    environment:
      #JAVA_TOOL_OPTIONS: -Xmx3500m
      TERM: dumb
      AWS_REGION: eu-west-1
      CFN_ASSIST_PROJECT: CfnAssist
      testEnvVar: testValue

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gradle-deps-{{ checksum "build.gradle" }}
      - run: gradle dependencies --no-daemon
      - run:
          name: integration
          command: gradle integration --no-daemon
      - store_test_results:
          path: ~/repo/build/test-results
      - store_artifacts:
          path: ~/repo/build/reports/tests
  acceptance:
    docker:
      - image: cimg/openjdk:21.0
    resource_class: medium
    working_directory: ~/repo

    environment:
      #JAVA_TOOL_OPTIONS: -Xmx3500m
      TERM: dumb
      AWS_REGION: eu-west-1
      CFN_ASSIST_PROJECT: CfnAssist
      testEnvVar: testValue

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gradle-deps-{{ checksum "build.gradle" }}
      - run: gradle dependencies --no-daemon
      - run:
          name: integration
          command: gradle acceptance --no-daemon
      - store_test_results:
          path: ~/repo/build/test-results
      - store_artifacts:
          path: ~/repo/build/reports/tests
  release:
    docker:
      - image: cimg/openjdk:21.0
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gradle-deps-{{ checksum "build.gradle" }}
      - run: gradle dependencies --no-daemon
      - go/install:
          version: 1.21.3
      - run:
          name: "Publish Release on GitHub"
          command: |
            go install github.com/tcnksm/ghr@latest
            gradle release
workflows:
  version: 2
  build:
    jobs:
      - build
      - integration:
          requires:
            - build
      - acceptance:
          requires:
            - integration
      - hold:
          type: approval
          requires:
            - acceptance
      - release:
          requires:
            - hold
