# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:15-jdk-buster
    resource_class: medium
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gradle-deps-{{ checksum "build.gradle" }}

      - run: gradle dependencies --no-daemon
      - run:
          name: unit
          command: gradle unit --no-daemon
      - store_test_results:
          path: ~/repo/build/test-results
      - store_artifacts:
          path: ~/repo/build/reports/tests